<?php

/**
 * Base class that represents a row from the 'model' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/24/11 11:02:20
 *
 * @package    lib.model.om
 */
abstract class BaseModel extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ModelPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the model_name field.
	 * @var        string
	 */
	protected $model_name;

	/**
	 * The value for the model_info field.
	 * @var        string
	 */
	protected $model_info;

	/**
	 * The value for the series_id field.
	 * @var        string
	 */
	protected $series_id;

	/**
	 * The value for the review_id field.
	 * @var        string
	 */
	protected $review_id;

	/**
	 * The value for the score_id field.
	 * @var        string
	 */
	protected $score_id;

	/**
	 * The value for the weight field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $weight;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Series
	 */
	protected $aSeries;

	/**
	 * @var        Review
	 */
	protected $aReview;

	/**
	 * @var        Score
	 */
	protected $aScore;

	/**
	 * @var        array Config[] Collection to store aggregation of Config objects.
	 */
	protected $collConfigs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collConfigs.
	 */
	private $lastConfigCriteria = null;

	/**
	 * @var        array Review[] Collection to store aggregation of Review objects.
	 */
	protected $collReviews;

	/**
	 * @var        Criteria The criteria used to select the current contents of collReviews.
	 */
	private $lastReviewCriteria = null;

	/**
	 * @var        array Score[] Collection to store aggregation of Score objects.
	 */
	protected $collScores;

	/**
	 * @var        Criteria The criteria used to select the current contents of collScores.
	 */
	private $lastScoreCriteria = null;

	/**
	 * @var        array UserMeta[] Collection to store aggregation of UserMeta objects.
	 */
	protected $collUserMetas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserMetas.
	 */
	private $lastUserMetaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ModelPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->weight = 0;
	}

	/**
	 * Initializes internal state of BaseModel object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [model_name] column value.
	 * 
	 * @return     string
	 */
	public function getModelName()
	{
		return $this->model_name;
	}

	/**
	 * Get the [model_info] column value.
	 * 
	 * @return     string
	 */
	public function getModelInfo()
	{
		return $this->model_info;
	}

	/**
	 * Get the [series_id] column value.
	 * 
	 * @return     string
	 */
	public function getSeriesId()
	{
		return $this->series_id;
	}

	/**
	 * Get the [review_id] column value.
	 * 
	 * @return     string
	 */
	public function getReviewId()
	{
		return $this->review_id;
	}

	/**
	 * Get the [score_id] column value.
	 * 
	 * @return     string
	 */
	public function getScoreId()
	{
		return $this->score_id;
	}

	/**
	 * Get the [weight] column value.
	 * 
	 * @return     int
	 */
	public function getWeight()
	{
		return $this->weight;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ModelPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [model_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setModelName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->model_name !== $v) {
			$this->model_name = $v;
			$this->modifiedColumns[] = ModelPeer::MODEL_NAME;
		}

		return $this;
	} // setModelName()

	/**
	 * Set the value of [model_info] column.
	 * 
	 * @param      string $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setModelInfo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->model_info !== $v) {
			$this->model_info = $v;
			$this->modifiedColumns[] = ModelPeer::MODEL_INFO;
		}

		return $this;
	} // setModelInfo()

	/**
	 * Set the value of [series_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setSeriesId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->series_id !== $v) {
			$this->series_id = $v;
			$this->modifiedColumns[] = ModelPeer::SERIES_ID;
		}

		if ($this->aSeries !== null && $this->aSeries->getId() !== $v) {
			$this->aSeries = null;
		}

		return $this;
	} // setSeriesId()

	/**
	 * Set the value of [review_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setReviewId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->review_id !== $v) {
			$this->review_id = $v;
			$this->modifiedColumns[] = ModelPeer::REVIEW_ID;
		}

		if ($this->aReview !== null && $this->aReview->getId() !== $v) {
			$this->aReview = null;
		}

		return $this;
	} // setReviewId()

	/**
	 * Set the value of [score_id] column.
	 * 
	 * @param      string $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setScoreId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->score_id !== $v) {
			$this->score_id = $v;
			$this->modifiedColumns[] = ModelPeer::SCORE_ID;
		}

		if ($this->aScore !== null && $this->aScore->getId() !== $v) {
			$this->aScore = null;
		}

		return $this;
	} // setScoreId()

	/**
	 * Set the value of [weight] column.
	 * 
	 * @param      int $v new value
	 * @return     Model The current object (for fluent API support)
	 */
	public function setWeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->weight !== $v || $this->isNew()) {
			$this->weight = $v;
			$this->modifiedColumns[] = ModelPeer::WEIGHT;
		}

		return $this;
	} // setWeight()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Model The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ModelPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Model The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ModelPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->weight !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->model_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->model_info = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->series_id = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->review_id = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->score_id = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->weight = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->created_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->updated_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = ModelPeer::NUM_COLUMNS - ModelPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Model object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSeries !== null && $this->series_id !== $this->aSeries->getId()) {
			$this->aSeries = null;
		}
		if ($this->aReview !== null && $this->review_id !== $this->aReview->getId()) {
			$this->aReview = null;
		}
		if ($this->aScore !== null && $this->score_id !== $this->aScore->getId()) {
			$this->aScore = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ModelPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ModelPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSeries = null;
			$this->aReview = null;
			$this->aScore = null;
			$this->collConfigs = null;
			$this->lastConfigCriteria = null;

			$this->collReviews = null;
			$this->lastReviewCriteria = null;

			$this->collScores = null;
			$this->lastScoreCriteria = null;

			$this->collUserMetas = null;
			$this->lastUserMetaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ModelPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseModel:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ModelPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseModel:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ModelPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseModel:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(ModelPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(ModelPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseModel:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ModelPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSeries !== null) {
				if ($this->aSeries->isModified() || $this->aSeries->isNew()) {
					$affectedRows += $this->aSeries->save($con);
				}
				$this->setSeries($this->aSeries);
			}

			if ($this->aReview !== null) {
				if ($this->aReview->isModified() || $this->aReview->isNew()) {
					$affectedRows += $this->aReview->save($con);
				}
				$this->setReview($this->aReview);
			}

			if ($this->aScore !== null) {
				if ($this->aScore->isModified() || $this->aScore->isNew()) {
					$affectedRows += $this->aScore->save($con);
				}
				$this->setScore($this->aScore);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ModelPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ModelPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ModelPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collConfigs !== null) {
				foreach ($this->collConfigs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collReviews !== null) {
				foreach ($this->collReviews as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collScores !== null) {
				foreach ($this->collScores as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserMetas !== null) {
				foreach ($this->collUserMetas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSeries !== null) {
				if (!$this->aSeries->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSeries->getValidationFailures());
				}
			}

			if ($this->aReview !== null) {
				if (!$this->aReview->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aReview->getValidationFailures());
				}
			}

			if ($this->aScore !== null) {
				if (!$this->aScore->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aScore->getValidationFailures());
				}
			}


			if (($retval = ModelPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collConfigs !== null) {
					foreach ($this->collConfigs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collReviews !== null) {
					foreach ($this->collReviews as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collScores !== null) {
					foreach ($this->collScores as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserMetas !== null) {
					foreach ($this->collUserMetas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ModelPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getModelName();
				break;
			case 2:
				return $this->getModelInfo();
				break;
			case 3:
				return $this->getSeriesId();
				break;
			case 4:
				return $this->getReviewId();
				break;
			case 5:
				return $this->getScoreId();
				break;
			case 6:
				return $this->getWeight();
				break;
			case 7:
				return $this->getCreatedAt();
				break;
			case 8:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ModelPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getModelName(),
			$keys[2] => $this->getModelInfo(),
			$keys[3] => $this->getSeriesId(),
			$keys[4] => $this->getReviewId(),
			$keys[5] => $this->getScoreId(),
			$keys[6] => $this->getWeight(),
			$keys[7] => $this->getCreatedAt(),
			$keys[8] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ModelPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setModelName($value);
				break;
			case 2:
				$this->setModelInfo($value);
				break;
			case 3:
				$this->setSeriesId($value);
				break;
			case 4:
				$this->setReviewId($value);
				break;
			case 5:
				$this->setScoreId($value);
				break;
			case 6:
				$this->setWeight($value);
				break;
			case 7:
				$this->setCreatedAt($value);
				break;
			case 8:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ModelPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setModelName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setModelInfo($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSeriesId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setReviewId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setScoreId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setWeight($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCreatedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUpdatedAt($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ModelPeer::DATABASE_NAME);

		if ($this->isColumnModified(ModelPeer::ID)) $criteria->add(ModelPeer::ID, $this->id);
		if ($this->isColumnModified(ModelPeer::MODEL_NAME)) $criteria->add(ModelPeer::MODEL_NAME, $this->model_name);
		if ($this->isColumnModified(ModelPeer::MODEL_INFO)) $criteria->add(ModelPeer::MODEL_INFO, $this->model_info);
		if ($this->isColumnModified(ModelPeer::SERIES_ID)) $criteria->add(ModelPeer::SERIES_ID, $this->series_id);
		if ($this->isColumnModified(ModelPeer::REVIEW_ID)) $criteria->add(ModelPeer::REVIEW_ID, $this->review_id);
		if ($this->isColumnModified(ModelPeer::SCORE_ID)) $criteria->add(ModelPeer::SCORE_ID, $this->score_id);
		if ($this->isColumnModified(ModelPeer::WEIGHT)) $criteria->add(ModelPeer::WEIGHT, $this->weight);
		if ($this->isColumnModified(ModelPeer::CREATED_AT)) $criteria->add(ModelPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(ModelPeer::UPDATED_AT)) $criteria->add(ModelPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ModelPeer::DATABASE_NAME);

		$criteria->add(ModelPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Model (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setModelName($this->model_name);

		$copyObj->setModelInfo($this->model_info);

		$copyObj->setSeriesId($this->series_id);

		$copyObj->setReviewId($this->review_id);

		$copyObj->setScoreId($this->score_id);

		$copyObj->setWeight($this->weight);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getConfigs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addConfig($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getReviews() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addReview($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getScores() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addScore($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserMetas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserMeta($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Model Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ModelPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ModelPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Series object.
	 *
	 * @param      Series $v
	 * @return     Model The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSeries(Series $v = null)
	{
		if ($v === null) {
			$this->setSeriesId(NULL);
		} else {
			$this->setSeriesId($v->getId());
		}

		$this->aSeries = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Series object, it will not be re-added.
		if ($v !== null) {
			$v->addModel($this);
		}

		return $this;
	}


	/**
	 * Get the associated Series object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Series The associated Series object.
	 * @throws     PropelException
	 */
	public function getSeries(PropelPDO $con = null)
	{
		if ($this->aSeries === null && (($this->series_id !== "" && $this->series_id !== null))) {
			$this->aSeries = SeriesPeer::retrieveByPk($this->series_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSeries->addModels($this);
			 */
		}
		return $this->aSeries;
	}

	/**
	 * Declares an association between this object and a Review object.
	 *
	 * @param      Review $v
	 * @return     Model The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setReview(Review $v = null)
	{
		if ($v === null) {
			$this->setReviewId(NULL);
		} else {
			$this->setReviewId($v->getId());
		}

		$this->aReview = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Review object, it will not be re-added.
		if ($v !== null) {
			$v->addModel($this);
		}

		return $this;
	}


	/**
	 * Get the associated Review object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Review The associated Review object.
	 * @throws     PropelException
	 */
	public function getReview(PropelPDO $con = null)
	{
		if ($this->aReview === null && (($this->review_id !== "" && $this->review_id !== null))) {
			$this->aReview = ReviewPeer::retrieveByPk($this->review_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aReview->addModels($this);
			 */
		}
		return $this->aReview;
	}

	/**
	 * Declares an association between this object and a Score object.
	 *
	 * @param      Score $v
	 * @return     Model The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setScore(Score $v = null)
	{
		if ($v === null) {
			$this->setScoreId(NULL);
		} else {
			$this->setScoreId($v->getId());
		}

		$this->aScore = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Score object, it will not be re-added.
		if ($v !== null) {
			$v->addModel($this);
		}

		return $this;
	}


	/**
	 * Get the associated Score object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Score The associated Score object.
	 * @throws     PropelException
	 */
	public function getScore(PropelPDO $con = null)
	{
		if ($this->aScore === null && (($this->score_id !== "" && $this->score_id !== null))) {
			$this->aScore = ScorePeer::retrieveByPk($this->score_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aScore->addModels($this);
			 */
		}
		return $this->aScore;
	}

	/**
	 * Clears out the collConfigs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addConfigs()
	 */
	public function clearConfigs()
	{
		$this->collConfigs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collConfigs collection (array).
	 *
	 * By default this just sets the collConfigs collection to an empty array (like clearcollConfigs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initConfigs()
	{
		$this->collConfigs = array();
	}

	/**
	 * Gets an array of Config objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Model has previously been saved, it will retrieve
	 * related Configs from storage. If this Model is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Config[]
	 * @throws     PropelException
	 */
	public function getConfigs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collConfigs === null) {
			if ($this->isNew()) {
			   $this->collConfigs = array();
			} else {

				$criteria->add(ConfigPeer::MODEL_ID, $this->id);

				ConfigPeer::addSelectColumns($criteria);
				$this->collConfigs = ConfigPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ConfigPeer::MODEL_ID, $this->id);

				ConfigPeer::addSelectColumns($criteria);
				if (!isset($this->lastConfigCriteria) || !$this->lastConfigCriteria->equals($criteria)) {
					$this->collConfigs = ConfigPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastConfigCriteria = $criteria;
		return $this->collConfigs;
	}

	/**
	 * Returns the number of related Config objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Config objects.
	 * @throws     PropelException
	 */
	public function countConfigs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collConfigs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ConfigPeer::MODEL_ID, $this->id);

				$count = ConfigPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ConfigPeer::MODEL_ID, $this->id);

				if (!isset($this->lastConfigCriteria) || !$this->lastConfigCriteria->equals($criteria)) {
					$count = ConfigPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collConfigs);
				}
			} else {
				$count = count($this->collConfigs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Config object to this object
	 * through the Config foreign key attribute.
	 *
	 * @param      Config $l Config
	 * @return     void
	 * @throws     PropelException
	 */
	public function addConfig(Config $l)
	{
		if ($this->collConfigs === null) {
			$this->initConfigs();
		}
		if (!in_array($l, $this->collConfigs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collConfigs, $l);
			$l->setModel($this);
		}
	}

	/**
	 * Clears out the collReviews collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addReviews()
	 */
	public function clearReviews()
	{
		$this->collReviews = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collReviews collection (array).
	 *
	 * By default this just sets the collReviews collection to an empty array (like clearcollReviews());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initReviews()
	{
		$this->collReviews = array();
	}

	/**
	 * Gets an array of Review objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Model has previously been saved, it will retrieve
	 * related Reviews from storage. If this Model is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Review[]
	 * @throws     PropelException
	 */
	public function getReviews($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReviews === null) {
			if ($this->isNew()) {
			   $this->collReviews = array();
			} else {

				$criteria->add(ReviewPeer::MODEL_ID, $this->id);

				ReviewPeer::addSelectColumns($criteria);
				$this->collReviews = ReviewPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ReviewPeer::MODEL_ID, $this->id);

				ReviewPeer::addSelectColumns($criteria);
				if (!isset($this->lastReviewCriteria) || !$this->lastReviewCriteria->equals($criteria)) {
					$this->collReviews = ReviewPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastReviewCriteria = $criteria;
		return $this->collReviews;
	}

	/**
	 * Returns the number of related Review objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Review objects.
	 * @throws     PropelException
	 */
	public function countReviews(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collReviews === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ReviewPeer::MODEL_ID, $this->id);

				$count = ReviewPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ReviewPeer::MODEL_ID, $this->id);

				if (!isset($this->lastReviewCriteria) || !$this->lastReviewCriteria->equals($criteria)) {
					$count = ReviewPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collReviews);
				}
			} else {
				$count = count($this->collReviews);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Review object to this object
	 * through the Review foreign key attribute.
	 *
	 * @param      Review $l Review
	 * @return     void
	 * @throws     PropelException
	 */
	public function addReview(Review $l)
	{
		if ($this->collReviews === null) {
			$this->initReviews();
		}
		if (!in_array($l, $this->collReviews, true)) { // only add it if the **same** object is not already associated
			array_push($this->collReviews, $l);
			$l->setModel($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Model is new, it will return
	 * an empty collection; or if this Model has previously
	 * been saved, it will retrieve related Reviews from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Model.
	 */
	public function getReviewsJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collReviews === null) {
			if ($this->isNew()) {
				$this->collReviews = array();
			} else {

				$criteria->add(ReviewPeer::MODEL_ID, $this->id);

				$this->collReviews = ReviewPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ReviewPeer::MODEL_ID, $this->id);

			if (!isset($this->lastReviewCriteria) || !$this->lastReviewCriteria->equals($criteria)) {
				$this->collReviews = ReviewPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastReviewCriteria = $criteria;

		return $this->collReviews;
	}

	/**
	 * Clears out the collScores collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addScores()
	 */
	public function clearScores()
	{
		$this->collScores = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collScores collection (array).
	 *
	 * By default this just sets the collScores collection to an empty array (like clearcollScores());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initScores()
	{
		$this->collScores = array();
	}

	/**
	 * Gets an array of Score objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Model has previously been saved, it will retrieve
	 * related Scores from storage. If this Model is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Score[]
	 * @throws     PropelException
	 */
	public function getScores($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collScores === null) {
			if ($this->isNew()) {
			   $this->collScores = array();
			} else {

				$criteria->add(ScorePeer::MODEL_ID, $this->id);

				ScorePeer::addSelectColumns($criteria);
				$this->collScores = ScorePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ScorePeer::MODEL_ID, $this->id);

				ScorePeer::addSelectColumns($criteria);
				if (!isset($this->lastScoreCriteria) || !$this->lastScoreCriteria->equals($criteria)) {
					$this->collScores = ScorePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastScoreCriteria = $criteria;
		return $this->collScores;
	}

	/**
	 * Returns the number of related Score objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Score objects.
	 * @throws     PropelException
	 */
	public function countScores(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collScores === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ScorePeer::MODEL_ID, $this->id);

				$count = ScorePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ScorePeer::MODEL_ID, $this->id);

				if (!isset($this->lastScoreCriteria) || !$this->lastScoreCriteria->equals($criteria)) {
					$count = ScorePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collScores);
				}
			} else {
				$count = count($this->collScores);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Score object to this object
	 * through the Score foreign key attribute.
	 *
	 * @param      Score $l Score
	 * @return     void
	 * @throws     PropelException
	 */
	public function addScore(Score $l)
	{
		if ($this->collScores === null) {
			$this->initScores();
		}
		if (!in_array($l, $this->collScores, true)) { // only add it if the **same** object is not already associated
			array_push($this->collScores, $l);
			$l->setModel($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Model is new, it will return
	 * an empty collection; or if this Model has previously
	 * been saved, it will retrieve related Scores from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Model.
	 */
	public function getScoresJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collScores === null) {
			if ($this->isNew()) {
				$this->collScores = array();
			} else {

				$criteria->add(ScorePeer::MODEL_ID, $this->id);

				$this->collScores = ScorePeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ScorePeer::MODEL_ID, $this->id);

			if (!isset($this->lastScoreCriteria) || !$this->lastScoreCriteria->equals($criteria)) {
				$this->collScores = ScorePeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastScoreCriteria = $criteria;

		return $this->collScores;
	}

	/**
	 * Clears out the collUserMetas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserMetas()
	 */
	public function clearUserMetas()
	{
		$this->collUserMetas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserMetas collection (array).
	 *
	 * By default this just sets the collUserMetas collection to an empty array (like clearcollUserMetas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserMetas()
	{
		$this->collUserMetas = array();
	}

	/**
	 * Gets an array of UserMeta objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Model has previously been saved, it will retrieve
	 * related UserMetas from storage. If this Model is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserMeta[]
	 * @throws     PropelException
	 */
	public function getUserMetas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserMetas === null) {
			if ($this->isNew()) {
			   $this->collUserMetas = array();
			} else {

				$criteria->add(UserMetaPeer::MODEL_ID, $this->id);

				UserMetaPeer::addSelectColumns($criteria);
				$this->collUserMetas = UserMetaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserMetaPeer::MODEL_ID, $this->id);

				UserMetaPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserMetaCriteria) || !$this->lastUserMetaCriteria->equals($criteria)) {
					$this->collUserMetas = UserMetaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserMetaCriteria = $criteria;
		return $this->collUserMetas;
	}

	/**
	 * Returns the number of related UserMeta objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserMeta objects.
	 * @throws     PropelException
	 */
	public function countUserMetas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserMetas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserMetaPeer::MODEL_ID, $this->id);

				$count = UserMetaPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserMetaPeer::MODEL_ID, $this->id);

				if (!isset($this->lastUserMetaCriteria) || !$this->lastUserMetaCriteria->equals($criteria)) {
					$count = UserMetaPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collUserMetas);
				}
			} else {
				$count = count($this->collUserMetas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UserMeta object to this object
	 * through the UserMeta foreign key attribute.
	 *
	 * @param      UserMeta $l UserMeta
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserMeta(UserMeta $l)
	{
		if ($this->collUserMetas === null) {
			$this->initUserMetas();
		}
		if (!in_array($l, $this->collUserMetas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserMetas, $l);
			$l->setModel($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Model is new, it will return
	 * an empty collection; or if this Model has previously
	 * been saved, it will retrieve related UserMetas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Model.
	 */
	public function getUserMetasJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ModelPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserMetas === null) {
			if ($this->isNew()) {
				$this->collUserMetas = array();
			} else {

				$criteria->add(UserMetaPeer::MODEL_ID, $this->id);

				$this->collUserMetas = UserMetaPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserMetaPeer::MODEL_ID, $this->id);

			if (!isset($this->lastUserMetaCriteria) || !$this->lastUserMetaCriteria->equals($criteria)) {
				$this->collUserMetas = UserMetaPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserMetaCriteria = $criteria;

		return $this->collUserMetas;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collConfigs) {
				foreach ((array) $this->collConfigs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collReviews) {
				foreach ((array) $this->collReviews as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collScores) {
				foreach ((array) $this->collScores as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserMetas) {
				foreach ((array) $this->collUserMetas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collConfigs = null;
		$this->collReviews = null;
		$this->collScores = null;
		$this->collUserMetas = null;
			$this->aSeries = null;
			$this->aReview = null;
			$this->aScore = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseModel:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseModel::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseModel
