<?php


/**
 * Skeleton subclass for representing a row from the 'device' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/08/11 12:26:41
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Device extends BaseDevice {
    
    public function __toString() {
        return $this->getName();
    }

} // Device
