<?php


/**
 * Skeleton subclass for performing query and update operations on the 'field_value' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/15/11 10:32:52
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FieldValuePeer extends BaseFieldValuePeer {
    
    public static function getFieldValue($fieldId, $configId)
    {
        $c = new Criteria();
        $c->add(FieldValuePeer::FIELD_ID, $fieldId);
        $c->add(FieldValuePeer::CONFIG_ID, $configId);
        
        if($value = FieldValuePeer::doSelectOne($c))
        {
            return $value;            
        }
        else
        {
            $value = new FieldValue;
            $value->setFieldId($fieldId);
            $value->setConfigId($configId);
            
            return $value;
        }
    }

} // FieldValuePeer
