<?php


/**
 * Skeleton subclass for representing a row from the 'page' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/08/11 12:26:44
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Page extends BasePage {
    
    function getParent(){
        return PagePeer::retrieveByPK($this->parent_id);	
    }

    function getChildren(){
        $c = new Criteria();
        return PagePeer::doSelect($c->add(PagePeer::PARENT_ID,$this->id));
    }

    function getSummary(){
        return strip_tags(substr($this->getContent(),0,100)."...");
    }


    /**
     * Initializes internal state of Page object.
     * @see        parent::__construct()
     */
    public function __construct()
    {
            // Make sure that parent constructor is always invoked, since that
            // is where any default values for this object are set.
            parent::__construct();
    }


    public function __toString()
    {
        return $this->getTitle();
    }

} // Page
