<?php


/**
 * Skeleton subclass for performing query and update operations on the 'series' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/08/11 12:26:46
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SeriesPeer extends BaseSeriesPeer {
    
    public static function isNew($seriesName)
    {
        $c = new Criteria();
        $c->add(SeriesPeer::SERIES_NAME, $seriesName, Criteria::EQUAL);
        
        $serieses = SeriesPeer::doSelect($c);
        
        if(count($serieses) > 0)
        {
            return false;
        }
        else
            return true;
    }
    
    
    public static function getSeriesByName($seriesName)
    {
        $c = new Criteria();
        $c->add(SeriesPeer::SERIES_NAME, $seriesName, Criteria::EQUAL);
        
        $series = SeriesPeer::doSelectOne($c);
        
        return $series;
    }
    
    static public function doSelect(Criteria $criteria, PropelPDO $con = null) {
        return parent::doSelect($criteria->addAscendingOrderByColumn(SeriesPeer::WEIGHT), $con);
    }

} // SeriesPeer
